# Generated by Django 4.2 on 2025-12-08 16:26

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresettoken_emailverificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Optional. Will be auto-generated from email if not provided.', max_length=150, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        # Remove unique constraint from username - allow duplicates since we use email as USERNAME_FIELD
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
    ]
